// Purpose: Index page for user profile

import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";
import Widgets from "@/components/Widgets";
import ProfileContainer from "@/components/ProfileContainer";

import { useSession, signIn } from "next-auth/react";

import Slider from "@mui/material/Slider";

export default function Home() {
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      signIn();
    },
  });
  const [userdata, setUserdata] = useState({
    username: "Rendering...",
    email: "Rendering...",
    userId: "Rendering...",
    password: "Rendering...",
    faculty: "Rendering...",
    followerlist: [],
    followinglist: [],
    year: 0,
  });
  useEffect(() => {
    fetch("/api/user/test")
      .then((res) => res.json())
      .then((data) => {
        setUserdata(data.data);
        console.log(session);
      });
  }, [session]);

  if (session) {
    return (
      <>
        <Head>
          <title>Twidemia</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/Twidemia-logo.png" />
        </Head>

        <main className="flex min-h-screen max-w-6xl w-full mx-auto">
          <ProfileContainer user={userdata} />
        </main>
      </>
    );
  }
}
