import Head from "next/head";
import dbConnect from "../lib/dbConnect";
import Feed from "@/components/Feed";
import Users from "@/components/Users";
import Widgets from "@/components/Widgets";
import Sidebar from "@/components/Sidebar";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";
import { useState, useEffect, useContext } from "react";
import { UserContext } from "@/pages/_app";

export default function Admin({ users: usersProp }) {
  const router = useRouter();
  const { data: session } = useSession();
  const users = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Twidemia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/Twidemia-logo.png" />
      </Head>

      <main className="grid grid-cols-5 min-h-screen max-w-7xl mx-auto gap-12">
        <div className="col-span-1">
          <Sidebar user={session.user} />
        </div>
        <div className="col-span-4">
          <Users users={users} />
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    // Try to connect the DB.
    await dbConnect();
    // const users = await User.find({});
    return {
      props: {
        // dbConnect
        // users: JSON.parse(JSON.stringify(users)) },
      },
    };
  } catch (e) {
    // If it cannot connect to DB, output log to console by using error flag.
    console.error(e);
  }
}

Admin.admin = true;
